### ISSUE TITLE
editorOptions.js http 문제입니다.

### ISSUE THREAD

**Issue by woosungchoi** [jakekwak/vditor-sv2#1]
162번째줄부터

```
  'n2-01': 'http://t1.daumcdn.net/liveboard/emoticon/kakaofriends/v1/niniz2/1.gif',
```

233번째 줄까지 위와 같이 `http://` 로 시작하는 것들이 있습니다.

전부 https로 바꾸는 것이 맞다고 생각합니다.

**Comment by jakekwak** [comment]
여기는 에디터만 들어 있습니다.  그누보드 연동관련 파일은 없는데,  알려 주셔서 감사합니다.
