### ISSUE TITLE
그누보드에서 textarea 문제

### ISSUE THREAD

**Issue by woosungchoi** [jakekwak/vditor-sv2#2]
확실히 말씀해주신

```
<textarea>
    <div>test</div>
</textarea>
```

<: \&lt; `&lt;`
\>: \&gt; `&gt;`

이 부분이 정말로 어렵네요.

그누보드에서 코드블럭내에 htmlpurifier 우회는 QnA에서 답을 얻었습니다.

https://sir.kr/qa/370328

여기 보시면 그누보드 코어를 건드려야 되지만.. 비교적 간단하게 처리 가능하네요.

마지막으로 textarea 문제만 해결하면 실사용하는데 전혀 문제가 없을 것 같습니다.

https://gnu.hubs.tk/bbs/board.php?bo_table=free&wr_id=18

현재로서는 위와 같은 결과가 나옵니다.

</textarea> 이후의 글 내용은 랜더링에서 제외됩니다.

**Comment by jakekwak** [comment]
어제 해 보니 우회안해도 됩니다.  conv_content(            ,0) 으로 들어가니 잘 됩니다. (textarea => div로)
오늘 wr_option과 data type set을 공부해 보겠습니다.

**Comment by woosungchoi** [comment]
`/bbs/view.php`

121번째 줄

```
$view['content'] = conv_content($view['wr_content'], $html);
```

를 바꾼다는 말인가요?

---

그리고 textarea는 

`/theme/basic-md/skin/board/basic-md/view.skin.php`

에서 

```
<textarea id="markdownText" class="preview" style="display:none;"><?php echo get_view_thumbnail($view['content']);?></textarea>
```

를

```
<div id="markdownText" class="preview" style="display:none;"><?php echo get_view_thumbnail($view['content']);?></div>
```

로 바꾼다는 말인가요?

div로 바꿔보니 다 깨지더라구요..

`conv_content`를 어떻게 만져야 될 것 같은데 알려주세요 ㅠㅠ

**Comment by jakekwak** [comment]
$html이 0이 되는 것이죠. class="preview contenteditable"로

**Comment by woosungchoi** [comment]
```
$view['content'] = conv_content($view['wr_content'], 0);
```

```
<div id="markdownText" class="preview contenteditable" style="display:none;"><?php echo get_view_thumbnail($view['content']);?></div>

```

아.. 이렇게 하니 잘 되네요!

문제라면... 기존에 적었던 글들이 전부 깨진다는 것입니다.

저는 기존 글들도 살리려고 하다보니 쉽지 않네요.

**Comment by jakekwak** [comment]
<br> 이 들어가서 그렇습니다.  wr_content안에 있는 <br>을 지워보세요

**Comment by woosungchoi** [comment]
> 이 들어가서 그렇습니다. wr_content안에 있는
> 을 지워보세요

내용이 안보여요 ㅠㅠ

**Comment by jakekwak** [comment]
\<br>

**Comment by woosungchoi** [comment]
`<br>` 을 게시글마다 지워야 된다는 말씀이신가요?

**Comment by jakekwak** [comment]
phpmyadmin들어가서 g5_write_[게시판]에서 wr_content 를 확인해 보세요.  어떤 데이타가 들어가 있는지.. 그안에서 문제가 되는 것을 쿼리나 백업해서 에디터로 한번에 고쳐서 다시 원위치 하면 됩니다.

**Comment by woosungchoi** [comment]
@jakekwak 

확실히 vditor에서 작성한 글은 문제없이 잘 되네요.

기존 다른 에디터로 작성한 것들이 좀 그렇긴하네요.

아무래도 textarea 부분 해결없이는 기존 글들을 작업하긴 해야겠네요.

감사합니다.

htmlpurifier도 원본으로 돌리면 되겠네요. 어짜피 text로 다 넘어가니..

해결되었습니다.

감사합니다!

**Comment by woosungchoi** [comment]
```
$view['content'] = conv_content($view['wr_content'], 0);
```

위와 같이 변경 후 보니깐

https://gnu.hubs.tk/bbs/board.php?bo_table=free&wr_id=23

위 링크를 보면 아시겠지만, 마인드맵과 차트가 정상적으로 출력되지 않습니다.

textarea 문제는 완전히 해결되었지만..  또 문제가 생기네요 ㅠㅠ

**Comment by woosungchoi** [comment]
https://gnu.hubs.tk/bbs/board.php?bo_table=free&wr_id=18

textarea 문제는 잘 해결되었습니다.

마인드맵과 차트가 왜 에러가 나는지 모르겠네요.

vditor 3.4까지 업그레이드 했습니다.

**Comment by woosungchoi** [comment]
아 그리고 원래 있는지는 기억이 안나지만 basic-md 테마에 basic-md 게시판스킨을 쓰니 코드 블록 밑에 스크롤바가 생기네요.

실제 스크롤은 없지만요.

**Comment by woosungchoi** [comment]
조만간 해결되겠네요.

기대됩니다!
