### ISSUE TITLE
마인드맵과 차트가 이상합니다.

### ISSUE THREAD

**Issue by woosungchoi** [jakekwak/vditor-sv2#5]
<: \&lt; `&lt;`
\>: \&gt; `&gt;`

```
<textarea>
    <div>test</div>
</textarea>
```

위 구문은 이제 문제없이 잘 나옵니다.

그런데 마인드맵과 차트가 이상하게 나오는군요 ㅠㅠ

vditor3.4 버전 및 3.0.12 버전 모두 이상하게 나오더라구요 ㅠㅠ

https://aced.ga/free/%EB%A7%88%ED%81%AC%EB%8B%A4%EC%9A%B4-%EB%8D%B0%EB%AA%A8/

**Comment by jakekwak** [comment]
가능하면 여기 깃헙은 그냥 에디터 관련 것만 올려 주세요.

그누보드와 연동된 이슈는 그누보드에 올려 주시면 감사하겠습니다.
